# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=next-ove
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/database/db:/data/db
      - ./data/mongo/database/dev.archive:/Databases/dev.archive
      - ./data/mongo/database/production:/Databases/production
      - ./data/mongo/mongo.keyfile:/data/mongo.keyfile
    command: mongod --replSet rs0 --keyFile /data/mongo.keyfile
  mongo-express:
    image: mongo-express:latest
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASSWORD}
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server --address ":9000" --console-address ":9001" /data
  static:
    build:
      context: static
      dockerfile: static/Dockerfile
    container_name: static
    ports:
      - "8082:8080"
  reverse-proxy:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    depends_on:
      - static
      - ove
      - ove-apps
    volumes:
      - ./config/dev.conf:/etc/nginx/conf.d/default.conf:ro
  ove:
    image: ovehub/ove:0.6.3-arm
    restart: unless-stopped
    environment:
      OVE_SPACES_JSON: ${OVE_SPACES}
      LOG_LEVEL: 2
    ports:
      - "9081:8080"
    depends_on:
      - static
  ove-apps:
    image: ovehub/ove-apps:0.6.4-arm
    restart: unless-stopped
    depends_on:
      - ove
    ports:
      - "9084:8084"
      - "9083:8083"
    environment:
      OVE_MAPS_LAYERS: "/run/secrets/MapLayers.json"
      OVE_NETWORKS_CONFIG_JSON: "/run/secrets/ove_networks_config.json"
      OVE_HOST: ${OVE_HOST}
      LOG_LEVEL: 2
    secrets:
      - ove_networks_config.json
      - MapLayers.json
secrets:
  ove_networks_config.json:
    file: config/ove_networks_config.json
  MapLayers.json:
    file: config/MapLayers.json