services:
  ove-core:
    image: next-ove/core:latest
    container_name: ove-core
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./apps/ove-core/config.production.json:/usr/src/app/config/config.json:ro
      - ./tools/db/.env.production:/usr/src/app/.env:ro
    env_file:
      apps/ove-core-ui/.env.docker
  ove-docs:
    image: next-ove/docs:latest
    container_name: ove-docs
    build:
      context: .
      dockerfile: tools/doc-viewer/Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8080"
    restart: "on-failure"
  ove-logs:
    image: next-ove/logs:latest
    container_name: ove-logs
    build:
      context: .
      dockerfile: apps/ove-logs/Dockerfile
    platform: linux/amd64
    ports:
      - "8082:8080"
    restart: "on-failure"
    volumes:
      - ./apps/ove-logs/.env.production:/usr/src/app/.env:ro


