version: "3"
services:
  ove-core:
    build:
      context: .
      dockerfile: ./apps/ove-core/Dockerfile
    ports:
      - "3333:3333"
    restart: "on-failure"
    volumes:
      - ./dist/apps/ove-core/config/config.json:/usr/src/app/config/config.json:ro
      - ./apps/ove-core/.env.production:/usr/src/app/.env:ro
  ove-core-ui:
    build:
      context: .
      dockerfile: ./apps/ove-core-ui/Dockerfile
    ports:
      - "8081:8080"
    restart: "on-failure"
