services:
  ove-core:
    image: next-ove/core:latest
    container_name: ove-core
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./apps/ove-core/config.production.json:/usr/src/app/config/config.json:ro
      - ./tools/db/.env.production:/usr/src/app/.env:ro
    env_file:
      apps/ove-core-ui/.env.docker
  ove-docs:
    image: next-ove/docs:latest
    container_name: ove-docs
    build:
      context: .
      dockerfile: tools/doc-viewer/Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8080"
    restart: "on-failure"
  ove-logs:
    image: next-ove/logs:latest
    container_name: ove-logs
    build:
      context: .
      dockerfile: apps/ove-logs/Dockerfile
    platform: linux/amd64
    ports:
      - "8082:8080"
    restart: "on-failure"
    volumes:
      - ./apps/ove-logs/.env.production:/usr/src/app/.env:ro
      - ./apps/ove-logs/config.json:/usr/src/config/config.json:ro
      - ./apps/ove-logs/data/logs.db:/usr/src/app/logs.db:rw
  ove-logs-db:
    image: postgres:18-alpine
    platform: linux/amd64
    env_file: ./apps/ove-logs/.env.postgres
    container_name: ove-logs-db
    restart: "unless-stopped"
    volumes:
      - ./apps/ove-logs/data/postgres:/var/lib/postgresql/18/docker
      - ./apps/ove-logs/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command:
      - postgres
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"


