version: "3"
services:
  ove-core:
    image: next-ove-core:latest
    ports:
      - "8080:8080"
    restart: "on-failure"
    volumes:
      - ./apps/ove-core/config.production.json:/usr/src/app/config/config.json:ro
      - ./tools/db/.env.production:/usr/src/app/.env:ro
    env_file:
      apps/ove-core-ui/.env.docker
  docs:
    build:
      context: .
      dockerfile: tools/doc-viewer/Dockerfile
    ports:
      - "8081:8080"
    restart: "on-failure"
    volumes:
      - ./tools/doc-viewer/.env.production:/usr/src/app/.env:ro
