ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - nx
  - puppeteer
  - sharp
  - sqlite3
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
