# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=next-ove
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
      - ./mongo.keyfile:/data/mongo.keyfile
    command: mongod --replSet rs0 --keyFile /data/mongo.keyfile
  mongo-express:
    image: mongo-express:latest
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASSWORD}
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server --address ":9000" --console-address ":9001" /data
  static:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: static
    ports:
      - "8082:8080"
  reverse-proxy:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./dev.conf:/etc/nginx/conf.d/default.conf:ro