listen_addresses = '*'    # listen on all interfaces, not just localhost
port = 5432               # default, but explicit is clearer
max_connections         = 200
shared_buffers          = 4GB
work_mem                = 50MB
maintenance_work_mem    = 1GB
wal_level               = minimal
synchronous_commit      = local
checkpoint_timeout      = 30min
max_wal_size            = 4GB
min_wal_size            = 1GB
effective_io_concurrency = 200
random_page_cost        = 1.1
max_wal_senders         = 0